# Generated by Django 5.0.3 on 2024-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_options_remove_persona_cc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
