# Generated by Django 5.0.3 on 2024-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CC',
            field=models.BigIntegerField(unique=True),
        ),
    ]
