# Generated by Django 5.0.3 on 2024-05-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('P_motos', models.IntegerField()),
                ('P_carros', models.IntegerField()),
                ('P_bicicletas', models.IntegerField()),
                ('P_emergencias', models.IntegerField()),
                ('P_otros', models.IntegerField()),
                ('P_discapacitados', models.IntegerField()),
                ('establecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
            ],
        ),
    ]
