# Generated by Django 5.0.3 on 2024-05-19 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vigilante',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vigilante',
            name='fecha_salida',
            field=models.DateField(default=None, null=True),
        ),
    ]
