# Generated by Django 5.0.3 on 2024-07-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pase', '0005_alter_pase_json_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pase',
            name='json_vehiculo',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='información del vehiculo a utilizar'),
        ),
    ]
