# Generated by Django 5.0.3 on 2024-07-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pase', '0006_alter_pase_json_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pase',
            name='nombre_vigilante',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='nombre del vigilante'),
        ),
        migrations.AlterField(
            model_name='pase',
            name='usuario_id',
            field=models.FloatField(null=True),
        ),
    ]
