# Generated by Django 5.0.3 on 2024-07-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pase', '0010_alter_pase_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pase',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
