# Generated by Django 5.0.3 on 2024-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pase', '0011_alter_pase_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pase',
            name='cc',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='cédula'),
        ),
        migrations.AlterField(
            model_name='pase',
            name='estado',
            field=models.IntegerField(choices=[(0, 'sin usar'), (1, 'procesandose'), (2, 'en uso'), (3, 'completado'), (4, 'perdido')], default=0),
        ),
        migrations.AlterField(
            model_name='pase',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='hora de entrada'),
        ),
        migrations.AlterField(
            model_name='pase',
            name='hora_salida',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='hora de salida'),
        ),
    ]
